interface XStylesBase {

    transition?: string | null;

    position?: 'relative' | 'absolute' | 'fixed' | null;
    flexGrow?: number | null;
    flexShrink?: number | null;
    flexBasis?: number | null;
    flexDirection?: 'row' | 'column' | null;
    flexWrap?: 'wrap' | 'nowrap' | null;
    alignSelf?: 'flex-start' | 'flex-end' | 'center' | 'stretch' | null;
    alignItems?: 'flex-start' | 'flex-end' | 'center' | 'stretch' | null;
    justifyContent?: 'flex-start' | 'flex-end' | 'center' | 'space-between' | null;
    top?: number | null;
    bottom?: number | null;
    left?: number | null;
    right?: number | null;
    margin?: number | null;
    marginVertical?: number | null;
    marginHorizontal?: number | null;
    marginTop?: number | null;
    marginBottom?: number | null;
    marginLeft?: number | null;
    marginRight?: number | null;
    padding?: number | null;
    paddingVertical?: number | null;
    paddingHorizontal?: number | null;
    paddingTop?: number | null;
    paddingBottom?: number | null;
    paddingLeft?: number | null;
    paddingRight?: number | null;
    height?: number | string | null;
    width?: number | string | null;
    minHeight?: number | string | null;
    minWidth?: number | string | null;
    maxHeight?: number | string | null;
    maxWidth?: number | string | null;
    zIndex?: number | null;
    borderRadius?: number | string | null;
    borderWidth?: number | null;
    borderColor?: string | null;
    cursor?: 'pointer';
    opacity?: number;
    color?: string | null;
    backgroundColor?: string | null;
    backgroundImage?: string | null;
    backgroundRepeat?: 'no-repeat' | 'repeat' | 'repeat-x' | 'repeat-y' | null;
    fontSize?: number | null;
    fontWeight?: '400' | '600';
    lineHeight?: number | string | null;
    overflow?: 'hidden' | null;
    textOverflow?: 'ellipsis' | null;
    whiteSpace?: 'nowrap' | null;
    textDecoration?: 'none' | 'underline' | null;
    textDecorationColor?: string | null;
}

interface XStylesHover {
    hoverPosition?: 'relative' | 'absolute' | 'fixed' | null;
    hoverFlexGrow?: number | null;
    hoverFlexShrink?: number | null;
    hoverFlexBasis?: number | null;
    hoverFlexDirection?: 'row' | 'column' | null;
    hoverFlexWrap?: 'wrap' | 'nowrap' | null;
    hoverAlignSelf?: 'flex-start' | 'flex-end' | 'center' | 'stretch' | null;
    hoverAlignItems?: 'flex-start' | 'flex-end' | 'center' | 'stretch' | null;
    hoverJustifyContent?: 'flex-start' | 'flex-end' | 'center' | 'space-between' | null;
    hoverTop?: number | null;
    hoverBottom?: number | null;
    hoverLeft?: number | null;
    hoverRight?: number | null;
    hoverMargin?: number | null;
    hoverMarginVertical?: number | null;
    hoverMarginHorizontal?: number | null;
    hoverMarginTop?: number | null;
    hoverMarginBottom?: number | null;
    hoverMarginLeft?: number | null;
    hoverMarginRight?: number | null;
    hoverPadding?: number | null;
    hoverPaddingVertical?: number | null;
    hoverPaddingHorizontal?: number | null;
    hoverPaddingTop?: number | null;
    hoverPaddingBottom?: number | null;
    hoverPaddingLeft?: number | null;
    hoverPaddingRight?: number | null;
    hoverHeight?: number | string | null;
    hoverWidth?: number | string | null;
    hoverMinHeight?: number | string | null;
    hoverMinWidth?: number | string | null;
    hoverMaxHeight?: number | string | null;
    hoverMaxWidth?: number | string | null;
    hoverZIndex?: number | null;
    hoverBorderRadius?: number | string | null;
    hoverBorderWidth?: number | null;
    hoverBorderColor?: string | null;
    hoverCursor?: 'pointer';
    hoverOpacity?: number;
    hoverColor?: string | null;
    hoverBackgroundColor?: string | null;
    hoverBackgroundImage?: string | null;
    hoverBackgroundRepeat?: 'no-repeat' | 'repeat' | 'repeat-x' | 'repeat-y' | null;
    hoverFontSize?: number | null;
    hoverFontWeight?: '400' | '600';
    hoverLineHeight?: number | string | null;
    hoverOverflow?: 'hidden' | null;
    hoverTextOverflow?: 'ellipsis' | null;
    hoverWhiteSpace?: 'nowrap' | null;
    hoverTextDecoration?: 'none' | 'underline' | null;
    hoverTextDecorationColor?: string | null;
}

interface XStylesSelected {
    selectedPosition?: 'relative' | 'absolute' | 'fixed' | null;
    selectedFlexGrow?: number | null;
    selectedFlexShrink?: number | null;
    selectedFlexBasis?: number | null;
    selectedFlexDirection?: 'row' | 'column' | null;
    selectedAlignSelf?: 'flex-start' | 'flex-end' | 'center' | 'stretch' | null;
    selectedAlignItems?: 'flex-start' | 'flex-end' | 'center' | 'stretch' | null;
    selectedJustifyContent?: 'flex-start' | 'flex-end' | 'center' | 'space-between' | null;
    selectedFlexWrap?: 'wrap' | 'nowrap' | null;
    selectedTop?: number | null;
    selectedBottom?: number | null;
    selectedLeft?: number | null;
    selectedRight?: number | null;
    selectedMargin?: number | null;
    selectedMarginVertical?: number | null;
    selectedMarginHorizontal?: number | null;
    selectedMarginTop?: number | null;
    selectedMarginBottom?: number | null;
    selectedMarginLeft?: number | null;
    selectedMarginRight?: number | null;
    selectedPadding?: number | null;
    selectedPaddingVertical?: number | null;
    selectedPaddingHorizontal?: number | null;
    selectedPaddingTop?: number | null;
    selectedPaddingBottom?: number | null;
    selectedPaddingLeft?: number | null;
    selectedPaddingRight?: number | null;
    selectedHeight?: number | string | null;
    selectedWidth?: number | string | null;
    selectedMinHeight?: number | string | null;
    selectedMinWidth?: number | string | null;
    selectedMaxHeight?: number | string | null;
    selectedMaxWidth?: number | string | null;
    selectedZIndex?: number | null;
    selectedBorderRadius?: number | string | null;
    selectedBorderWidth?: number | null;
    selectedBorderColor?: string | null;
    selectedCursor?: 'pointer';
    selectedOpacity?: number;
    selectedColor?: string | null;
    selectedBackgroundColor?: string | null;
    selectedBackgroundImage?: string | null;
    selectedBackgroundRepeat?: 'no-repeat' | 'repeat' | 'repeat-x' | 'repeat-y' | null;
    selectedFontSize?: number | null;
    selectedFontWeight?: '400' | '600';
    selectedLineHeight?: number | string | null;
    selectedOverflow?: 'hidden' | null;
    selectedTextOverflow?: 'ellipsis' | null;
    selectedWhiteSpace?: 'nowrap' | null;
    selectedTextDecoration?: 'none' | 'underline' | null;
    selectedTextDecorationColor?: string | null;
}

interface XStylesSelectedHover {
    selectedHoverPosition?: 'relative' | 'absolute' | 'fixed' | null;
    selectedHoverFlexGrow?: number | null;
    selectedHoverFlexShrink?: number | null;
    selectedHoverFlexBasis?: number | null;
    selectedHoverFlexDirection?: 'row' | 'column' | null;
    selectedHoverAlignSelf?: 'flex-start' | 'flex-end' | 'center' | 'stretch' | null;
    selectedHoverAlignItems?: 'flex-start' | 'flex-end' | 'center' | 'stretch' | null;
    selectedHoverJustifyContent?: 'flex-start' | 'flex-end' | 'center' | 'space-between' | null;
    selectedHoverFlexWrap?: 'wrap' | 'nowrap' | null;
    selectedHoverTop?: number | null;
    selectedHoverBottom?: number | null;
    selectedHoverLeft?: number | null;
    selectedHoverRight?: number | null;
    selectedHoverMargin?: number | null;
    selectedHoverMarginVertical?: number | null;
    selectedHoversMarginHorizontal?: number | null;
    selectedHoverMarginTop?: number | null;
    selectedHoverMarginBottom?: number | null;
    selectedHoverMarginLeft?: number | null;
    selectedHoverMarginRight?: number | null;
    selectedHoverPadding?: number | null;
    selectedHoverPaddingVertical?: number | null;
    selectedHoverPaddingHorizontal?: number | null;
    selectedHoverPaddingTop?: number | null;
    selectedHoverPaddingBottom?: number | null;
    selectedHoverPaddingLeft?: number | null;
    selectedHoverPaddingRight?: number | null;
    selectedHoverHeight?: number | string | null;
    selectedHoverWidth?: number | string | null;
    selectedHoverMinHeight?: number | string | null;
    selectedHoverMinWidth?: number | string | null;
    selectedHoverMaxHeight?: number | string | null;
    selectedHoverMaxWidth?: number | string | null;
    selectedHoverZIndex?: number | null;
    selectedHoverBorderRadius?: number | string | null;
    selectedHoverBorderWidth?: number | null;
    selectedHoverBorderColor?: string | null;
    selectedHoverCursor?: 'pointer';
    selectedHoverOpacity?: number;
    selectedHoverColor?: string | null;
    selectedHoverBackgroundColor?: string | null;
    selectedHoverBackgroundImage?: string | null;
    selectedHoverBackgroundRepeat?: 'no-repeat' | 'repeat' | 'repeat-x' | 'repeat-y' | null;
    selectedHoverFontSize?: number | null;
    selectedHoverFontWeight?: '400' | '600';
    selectedHoverLineHeight?: number | string | null;
    selectedHoverOverflow?: 'hidden' | null;
    selectedHoverTextOverflow?: 'ellipsis' | null;
    selectedHoverWhiteSpace?: 'nowrap' | null;
    selectedHoverTextDecoration?: 'none' | 'underline' | null;
    selectedHoverTextDecorationColor?: string | null;
}

export interface XStyles extends XStylesBase, XStylesHover, XStylesSelected, XStylesSelectedHover {

};